// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfRL8yW1fmquTVL7MjjhuZ9KySYn7u9U',
    appId: '1:413811014873:web:5fad4a9aa08236012592c8',
    messagingSenderId: '413811014873',
    projectId: 'data-entry-mob-app',
    authDomain: 'data-entry-mob-app.firebaseapp.com',
    storageBucket: 'data-entry-mob-app.firebasestorage.app',
    measurementId: 'G-S22LBTZFFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpmj2Mh6j0BPtJEwDL1tyMyxv2Fca1jpU',
    appId: '1:413811014873:android:0795e8c0f35b69962592c8',
    messagingSenderId: '413811014873',
    projectId: 'data-entry-mob-app',
    storageBucket: 'data-entry-mob-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZyjKiMYUfDR_ME6N1cEEa3H7pscYXvQ',
    appId: '1:413811014873:ios:8cee2958b25ac5b92592c8',
    messagingSenderId: '413811014873',
    projectId: 'data-entry-mob-app',
    storageBucket: 'data-entry-mob-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHfRL8yW1fmquTVL7MjjhuZ9KySYn7u9U',
    appId: '1:413811014873:web:ecaf87ae12d2bd3c2592c8',
    messagingSenderId: '413811014873',
    projectId: 'data-entry-mob-app',
    authDomain: 'data-entry-mob-app.firebaseapp.com',
    storageBucket: 'data-entry-mob-app.firebasestorage.app',
    measurementId: 'G-N6PRCQ50J2',
  );
}
